services:
  rocket-market-db:
    container_name: rocket-market-db
    image: mysql:latest
    restart: always
    volumes:
      - mysql_volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3308:3306"
    networks:
      - docker-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G

  rocket-market-app:
    container_name: rocket-market-app
    ports:
      - "8081:8080"
    image: cheoneunjeong/rocket-market-api:latest
#    volumes:
#      - rocket-market-images:/app/images
    networks:
      - docker-network
    depends_on:
      rocket-market-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G

networks:
  docker-network:
    driver: bridge

volumes:
  mysql_volume:
    driver: local
#  rocket-market-images:
#    driver: local